# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- release/*
- feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'


- script: |
    npm install -g @angular/cli
  displayName: 'install angular/cli'

- script: |
    npm install
  displayName: 'install angular/cli'
  condition: eq(variables['CachRestored'],False)

- task: Cache@2
  inputs:
    key: '**/package-lock.json, !**/node_modules/**/package-lock.json, !**/.*/**/package-lock.json'
    path: '$(System.DefaultWorkingDirectory)/node_modules'
    restoreKeys: 'CachRestored'

- script: |
    ng build --prod --output-path $(Build.BinariesDirectory)/dist
  displayName: 'npm build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.BinariesDirectory)/dist'
    ArtifactName: 'artifacts'
    publishLocation: 'Container'